import type { Asset } from '../api/types';

export interface ExtendedAsset extends Asset {
  priority?: 'high' | 'medium' | 'low';
  scheduled_for?: string;
  published_post_id?: string;
  published_at?: string;
  rejection_reason?: string;
  rejection_note?: string;
  history?: Array<{
    timestamp: string;
    action: string;
    actor: string;
    note?: string;
  }>;
}

export const INITIAL_ASSETS: ExtendedAsset[] = [
  {
    id: 'asset_jade_fail_001',
    campaign_id: 'camp_jade_001',
    brand_id: 'jade',
    platform: 'linkedin',
    content_type: 'post',
    variant: 'A',
    language: 'en',
    priority: 'high',
    title: 'Complete Protection for High-Value Jewellers',
    body: 'JA Assure guarantees complete protection for your jewellery business with zero risk of loss. Our bespoke vault coverage leaves nothing to chance.',
    hashtags: ['#JewelleryInsurance', '#RiskManagement', '#FineArt', '#LuxurySecurity'],
    media_url: null,
    status: 'compliance_failed',
    compliance: {
      result: 'FAIL',
      risk: 'HIGH',
      rules: ['CLAIM_001', 'ABS_004'],
      issues: [
        {
          rule_id: 'CLAIM_001',
          reason: 'Guaranteed outcome: Promising "guarantees complete protection" and "zero risk" violates statutory insurance advisory guidelines.',
          text: 'JA Assure guarantees complete protection for your jewellery business with zero risk of loss.'
        }
      ],
      suggested_revision:
        'JA Assure can help businesses understand and manage relevant risks. Our bespoke vault coverage provides robust contingency planning tailored to high-value collections.'
    },
    created_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    approved_at: null,
    approved_by: null,
    history: [
      {
        timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        action: 'Generated by Content Agent',
        actor: 'Content Agent (Claude/Gemini)'
      },
      {
        timestamp: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
        action: 'Compliance Check: FAILED',
        actor: 'Compliance Agent',
        note: 'Flagged CLAIM_001: Unsupported absolute guarantee'
      }
    ]
  },
  {
    id: 'asset_jade_002',
    campaign_id: 'camp_jade_001',
    brand_id: 'jade',
    platform: 'linkedin',
    content_type: 'post',
    variant: 'B',
    language: 'en',
    priority: 'high',
    title: 'Understanding Vault Risk Profiles',
    body: 'Protecting high-value jewellery begins long before a claim is made.\n\nEvery jewellery business carries risk. The question is whether that risk has been properly understood, categorized, and systematically mitigated across handling, showroom display, and secure transit.\n\nOur underwriters work alongside master jewellers across Southeast Asia to audit physical vault architecture and protocol redundancies.\n\nSpeak with our high-value asset specialists to review your institutional risk schedule.',
    hashtags: ['#JewelleryRisk', '#AssetProtection', '#B2BSpecialist', '#JAAssureJade'],
    media_url: null,
    status: 'pending_review',
    compliance: {
      result: 'PASS',
      risk: 'LOW',
      rules: ['CLAIM_001', 'TONE_005', 'CTA_006', 'PROD_007'],
      issues: [],
      suggested_revision: null
    },
    created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    approved_at: null,
    approved_by: null,
    history: [
      {
        timestamp: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
        action: 'Generated by Content Agent',
        actor: 'Content Agent'
      },
      {
        timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
        action: 'Compliance Check: PASS',
        actor: 'Compliance Agent'
      }
    ]
  },
  {
    id: 'asset_doc_001',
    campaign_id: 'camp_doc_001',
    brand_id: 'doctorshield',
    platform: 'instagram',
    content_type: 'caption',
    variant: 'A',
    language: 'en',
    priority: 'medium',
    title: 'Three Things Doctors Should Know About Inquiries',
    body: 'Three things doctors should know when facing a medical inquiry:\n\n1. Early legal counsel preserves clinical documentation integrity and reduces procedural anxiety.\n2. Disciplinary committees scrutinize peer-reviewed standards of clinical practice.\n3. DoctorShield provides calm, experienced medico-legal guidance every step of the journey, ensuring your professional reputation is defended with diligence.\n\nYour clinical focus belongs with your patients. Let our dedicated legal specialists support your practice.',
    hashtags: ['#DoctorShield', '#MedicalIndemnity', '#DoctorWellbeing', '#HealthcareLaw', '#ClinicRisk'],
    media_url: '/assets/demo-doc.jpg',
    status: 'pending_review',
    compliance: {
      result: 'PASS',
      risk: 'LOW',
      rules: ['TONE_005', 'PROD_007', 'RUN_012'],
      issues: [],
      suggested_revision: null
    },
    created_at: new Date(Date.now() - 48 * 60 * 1000).toISOString(),
    approved_at: null,
    approved_by: null,
    history: [
      {
        timestamp: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
        action: 'Generated by Content Agent',
        actor: 'Content Agent'
      },
      {
        timestamp: new Date(Date.now() - 48 * 60 * 1000).toISOString(),
        action: 'Compliance Check: PASS',
        actor: 'Compliance Agent'
      }
    ]
  },
  {
    id: 'asset_transit_001',
    campaign_id: 'camp_jag_001',
    brand_id: 'jaguar',
    platform: 'linkedin',
    content_type: 'post',
    variant: 'A',
    language: 'en',
    priority: 'medium',
    title: 'Cross-Border Cargo Chain of Custody in ASEAN',
    body: 'In bonded transit between Singapore and Kuala Lumpur, handover checkpoints are where 68% of discrepancies occur.\n\nJaguar Transit combines multi-sensor telemetry tracking with real-time underwriting endorsements to keep your high-value cargo protected door-to-door.\n\nFrom tamper-evident seal verification to expedited customs bonded corridor handling, our logistics desk provides the operational rigor required by modern supply chains.\n\nRequest a corridor risk assessment with our freight underwriters.',
    hashtags: ['#LogisticsRisk', '#FreightSecurity', '#ASEANTrade', '#SupplyChainSafety'],
    media_url: null,
    status: 'approved',
    compliance: {
      result: 'PASS',
      risk: 'LOW',
      rules: ['CLAIM_001', 'STAT_002', 'JUR_011'],
      issues: [],
      suggested_revision: null
    },
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    approved_at: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    approved_by: 'Marcus Chen (Head of Ops)',
    history: [
      {
        timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
        action: 'Generated',
        actor: 'Content Agent'
      },
      {
        timestamp: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
        action: 'Approved for Publishing',
        actor: 'Marcus Chen'
      }
    ]
  },
  {
    id: 'asset_transit_002',
    campaign_id: 'camp_jag_001',
    brand_id: 'jaguar',
    platform: 'x',
    content_type: 'post',
    variant: 'A',
    language: 'en',
    priority: 'low',
    title: 'Border Clearance Telemetry',
    body: 'High-value logistics is not about hope—it is about verifiable telemetry and bonded protocol enforcement. How is your cargo secured at cross-border customs clearances?\n\nJaguar Transit provides continuous digital custody verification across ASEAN corridors.',
    hashtags: ['#Logistics', '#CargoProtection', '#SupplyChain'],
    media_url: null,
    status: 'scheduled',
    scheduled_for: 'Tomorrow · 10:30 AM',
    compliance: {
      result: 'PASS',
      risk: 'LOW',
      rules: ['CLAIM_001', 'TONE_005'],
      issues: [],
      suggested_revision: null
    },
    created_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    approved_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    approved_by: 'Marcus Chen (Head of Ops)',
    history: [
      {
        timestamp: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
        action: 'Scheduled for Project 2 Publishing',
        actor: 'Marcus Chen'
      }
    ]
  },
  {
    id: 'asset_doc_002',
    campaign_id: 'camp_doc_001',
    brand_id: 'doctorshield',
    platform: 'linkedin',
    content_type: 'article',
    variant: 'A',
    language: 'en',
    priority: 'low',
    title: 'Navigating Telemedicine Consent and Medico-Legal Bounds',
    body: 'As tele-consultations expand across Singapore and Malaysia, practitioner documentation standards remain identical to in-person clinics.\n\nIn our latest clinical risk brief, we outline three critical protocols for remote consent capture and electronic health record archiving to safeguard both practitioner and patient.',
    hashtags: ['#DoctorShield', '#Telehealth', '#ClinicalGovernance', '#MedicalPractice'],
    media_url: null,
    status: 'published',
    published_post_id: 'demo_ja_28491',
    published_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    compliance: {
      result: 'PASS',
      risk: 'LOW',
      rules: ['CLAIM_001', 'TONE_005', 'REG_010'],
      issues: [],
      suggested_revision: null
    },
    created_at: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
    approved_at: new Date(Date.now() - 25 * 3600 * 1000).toISOString(),
    approved_by: 'Dr. Sarah Lim (Medical Advisory Lead)',
    history: [
      {
        timestamp: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
        action: 'Published via Simulated Publisher',
        actor: 'System (Project 2)',
        note: 'Post ID: demo_ja_28491'
      }
    ]
  },
  {
    id: 'asset_jade_004',
    campaign_id: 'camp_jade_002',
    brand_id: 'jade',
    platform: 'instagram',
    content_type: 'carousel',
    variant: 'A',
    language: 'en',
    priority: 'medium',
    title: 'Behind the Vault: The Science of High-Value Gem Storage',
    body: 'Slide 1: Not all vaults are created equal. Discover the 4 parameters high-net-worth collectors monitor.\nSlide 2: Humidity and thermal stabilization for emeralds and pearls.\nSlide 3: Dual-key biometric verification protocols.\nSlide 4: Transit-to-vault transition risks during regional art fairs.\n\nProtect your legacy with bespoke underwriting from Jade.',
    hashtags: ['#JadeInsurance', '#VaultSecurity', '#FineJewellery', '#LuxuryAssets'],
    media_url: null,
    status: 'pending_review',
    compliance: {
      result: 'PASS',
      risk: 'LOW',
      rules: ['TONE_005', 'PROD_007'],
      issues: [],
      suggested_revision: null
    },
    created_at: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    approved_at: null,
    approved_by: null
  },
  {
    id: 'asset_jade_005',
    campaign_id: 'camp_jade_002',
    brand_id: 'jade',
    platform: 'blog',
    content_type: 'article',
    variant: 'A',
    language: 'en',
    priority: 'low',
    title: 'Consignment & Exhibition Risk: An Underwriter Perspective',
    body: 'When fine jewellery leaves permanent vault custody for international exhibitions, traditional commercial policies often exhibit critical coverage gaps.\n\nIn this editorial guide, Jade specialists review wall-to-wall insurance clauses, courier custody agreements, and customs transit indemnities.',
    hashtags: ['#JewelleryExhibitions', '#ArtFairInsurance', '#JAAssure'],
    media_url: null,
    status: 'approved',
    compliance: {
      result: 'PASS',
      risk: 'LOW',
      rules: ['CLAIM_001', 'TONE_005', 'COV_008'],
      issues: [],
      suggested_revision: null
    },
    created_at: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    approved_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    approved_by: 'Marcus Chen'
  }
];
